import sys

dll = r'D:\编程开发\开源项目\多维表分析软件\MultiTableAddin\dist\files\MultiTableAddin.dll'
data = open(dll, 'rb').read()

def has(s, enc='utf-8'):
    try:
        b = s.encode(enc)
    except Exception:
        b = s.encode('latin-1')
    return b in data

def missing(s, enc='utf-8'): return not has(s, enc)

print('DLL:', dll, 'size=', len(data))
checks = [
    ('Version 2.9.39 (UTF-16LE)', '2.9.39', 'utf-16le'),
    ('ReleaseDate 2026-08-20 (UTF-16LE)', '2026-08-20', 'utf-16le'),
    ('CodeName StablePath (UTF-16LE)', 'StablePath', 'utf-16le'),
    # --- v2.9.3 / WindowUX prior features still present ---
    ('addRow uses showDraftDetailPanel({})', 'showDraftDetailPanel({})', 'utf-8'),
    ('Gantt multi-column CSS gantt-ctrl-row', 'gantt-ctrl-row', 'utf-8'),
    ('Gantt frozen left gantt-left', 'gantt-left', 'utf-8'),
    ('Gantt upper label text', '上层标签：周视图→月份', 'utf-8'),
    ('Calendar no auto-close lastRenderedViewId', 'lastRenderedViewId', 'utf-8'),
    ('Calendar current line all columns todayInView', 'todayInView', 'utf-8'),
    ('Calendar drag no openTable revert', "openTable(state.sheet, state.table)", 'utf-8'),
    ('Kanban label toggle showFieldLabels', 'showFieldLabels', 'utf-8'),
    ('Dashboard chart padding padB=24', 'padB=24', 'utf-8'),
    ('Dashboard theme DASH_THEME_LIST', 'DASH_THEME_LIST', 'utf-8'),
    ('Dashboard theme getDashColors', 'getDashColors', 'utf-8'),
    ('Gantt today-line overlay gantt-overlay', 'gantt-overlay', 'utf-8'),
    ('Gantt column menu showColMenu', 'showColMenu', 'utf-8'),
    ('Window follow Excel minimize AttachExcelMinimizeFollow', 'HtmlMainForm.MinimizeFollow.Attach', 'utf-16le'),
    ('Window setOpenMaximized API', 'setOpenMaximized', 'utf-16le'),
    ('Window addField API', 'addField', 'utf-16le'),
    # --- v2.9.4 / UXPolish new features ---
    ('Calendar 15-min snap param snapMinutes', 'snapMinutes', 'utf-8'),
    ('Calendar datetime date fields isAnyCalendarDateField', 'isAnyCalendarDateField', 'utf-8'),
    ('DateTime split input buildDateTimeSplitInput', 'buildDateTimeSplitInput', 'utf-8'),
    ('Generic record context menu showRecordContextMenu', 'showRecordContextMenu', 'utf-8'),
    ('Gantt row selected highlight .gantt-row.selected', '.gantt-row.selected', 'utf-8'),
    ('Calendar snap setting label 时间步进', '时间步进', 'utf-8'),
    ('About window intro 基于 Excel/WPS 超级表', '基于 Excel/WPS 超级表', 'utf-8'),
    ('Form new/next merge formNewRecord', 'formNewRecord', 'utf-8'),
    ('Calendar drag live updateCalEventTime', 'updateCalEventTime', 'utf-8'),
    ('Calendar drag dayBaseOf', 'dayBaseOf', 'utf-8'),
    # --- ribbon / icon (v2.9.4) ---
    ('Ribbon label 多维表', 'label="多维表"', 'utf-8'),
    ('RibbonOpen.png resource name', 'MultiTableAddin.Resources.RibbonOpen.png', 'utf-8'),
    ('RibbonAbout.png resource removed-from-use', 'MultiTableAddin.Resources.RibbonAbout.png', 'utf-8'),
    # --- v2.9.5 / UXPolish #9~#14 ---
    ('#9 form-nav nowrap', 'flex-wrap:nowrap;overflow-x:auto', 'utf-8'),
    ('#10 date-edit blue accent', 'cell-edit.date-edit{accent-color:#3370FF;}', 'utf-8'),
    ('#10 wheel 1-month step in custom HTML picker', 'moveMonth(disp, dir)', 'utf-8'),
    ('#11 gantt group label class', 'gantt-group-label', 'utf-8'),
    ('#12 col-menu binds focus col', '记住焦点列', 'utf-8'),
    ('#13 sidebar 115px', 'width:115px', 'utf-8'),
    ('#13 settings above refresh', 'toggleSettingsPanel(set)', 'utf-8'),
    ('#14 gantt icon GTST viewBox', '0 0 70.87 70.86', 'utf-8'),
    ('#14 dashboard icon YBP evenodd', 'M12.89,60.55', 'utf-8'),
    ('#14 TableSpark RibbonOpen png baked', 'MultiTableAddin.Resources.RibbonOpen.png', 'utf-8'),
    # --- v2.9.6 / Phase B #1~#15 ---
    ('#1 dashboard hide labels <= labelHideThreshold', 'g.value > (APP_SETTINGS.labelHideThreshold || 0)', 'utf-8'),
    ('#2 calendar view buttons day/week/month', 'id="calDay" title="日视图">日</button><button class="btn sm\'+(view===\'week\'?\' active\':\'\')+\'" id="calWeek" title="周视图">周</button><button class="btn sm\'+(view===\'month\'?\' active\':\'\')+\'" id="calMonth" title="月视图">月', 'utf-8'),
    ('#3 day view drag uses minutes not pixels', 'origStart.getHours()*60+origStart.getMinutes()', 'utf-8'),
    ('#4 week view today column no fill (empty rule)', '.cal-day-col.today:not(.is-week){}', 'utf-8'),
    ('#5 calendar settings aligned labels', '.setting-row label{flex:0 0 132px;width:132px;min-width:132px;max-width:132px;', 'utf-8'),
    ('#6 kanban drag card no tilt', '.kanban-card.dragging{opacity:.65;box-shadow:0 8px 24px rgba(0,0,0,.15);', 'utf-8'),
    ('#7 table summary row function', 'renderSummaryRow', 'utf-8'),
    ('#7 table summary row CSS', 'table.grid.sticky-summary tfoot td{position:sticky;bottom:0', 'utf-8'),
    ('#7 table summary showSummary state', 'showSummary', 'utf-8'),
    ('#8 field type switch no longer reverts', 'f.type=typeSel.value; buildForm(f)', 'utf-8'),
    ('#15 RibbonOpen.png resource', 'MultiTableAddin.Resources.RibbonOpen.png', 'utf-8'),
    ('#15 AppIcon.ico resource', 'MultiTableAddin.Resources.AppIcon.ico', 'utf-8'),
    # --- Phase C C1~C11 ---
    ('C1 batch field props editor', 'function showBatchFieldEditor', 'utf-8'),
    ('C2 datetime default 00:00 (select)', "tSel.value='00:00'", 'utf-8'),
    ('C3 gantt range zoom levels', 'var span={day:3, week:21, month:70}[dim]||70;', 'utf-8'),
    ('C4 color field persistence', 'calendarConfig.colorField', 'utf-8'),
    ('C5 kanban drag no text select', 'body.kanban-dragging', 'utf-8'),
    ('C7b gallery image folder', 'cardMeta.imageFolder', 'utf-8'),
    ('C8 field settings focus follow', 'focusFieldInSettings', 'utf-8'),
    ('C9 gantt range year branch anchor', 'var yy = a.getFullYear();', 'utf-8'),
    ('C10 help WPS mention', '基于 Excel/WPS 超级表', 'utf-8'),
    ('C11 RibbonOpen png resource', 'MultiTableAddin.Resources.RibbonOpen.png', 'utf-8'),
    # --- D batch (v2.9.7) ---
    ('D1 gantt quarter button', "['quarter','季']", 'utf-8'),
    ('D2 chart minLabelValue model', 'MinLabelValue', 'utf-8'),
    ('D3 window default maximized', 'FormWindowState', 'utf-8'),
    ('D4 summary position model', 'SummaryPosition', 'utf-8'),
    ('D5 calendar selected gallery style', 'box-shadow:0 0 0 2px var(--accent);z-index:3;', 'utf-8'),
    ('D6 kanban drag update displayTexts', 'delete r.displayTexts[u.field]', 'utf-8'),
    ('D7 batch editor modal width 1040px', "modal.style.width='1200px'", 'utf-8'),
    # --- v2.9.7 feedback fixes #284~#295 (13 items) ---
    ('#284 window default openMaximized true', 'openMaximized:true', 'utf-8'),
    ('#284 global settings labelHideThreshold default', 'labelHideThreshold:0', 'utf-8'),
    # ('#284 global settings summaryPosition default' 已迁移为文件级设置，见 #366 下方检查项)
    ('#285 gantt today line 2px (unified with calendar)', ".gantt-today-line{position:absolute;top:0;bottom:0;width:2px;background:#F53F3F;z-index:6;pointer-events:none;box-sizing:border-box;}", 'utf-8'),
    ('#286 gantt quarter label Q1-Q4', "'第'+['一','二','三','四'][Math.floor(t.getMonth()/3)]+'季度'", 'utf-8'),
    ('#286 gantt tickLabel year branch', "if(dim==='year') return ''+t.getFullYear()", 'utf-8'),
    ('#286 gantt range year branch', 'min:new Date(yy-2,0,1), max:new Date(yy+2,11,31,23,59,59)', 'utf-8'),
    ('#287/#288/#347/#367 label threshold control now in chart settings modal', "thInp.id='setLabelThresholdModal'", 'utf-8'),
    # ('#287/#288 settings summary position control' 已迁移为文件级设置，见 #366 下方检查项)
    ('#289 no save when cell unchanged normCellVal', 'function normCellVal(v){', 'utf-8'),
    ('#290 search results panel', '<div class="search-results" id="searchResults">', 'utf-8'),
    ('#290 updateRightCol toggle has-panel', 'function updateRightCol(){', 'utf-8'),
    ('#290 renderSearchResults function', 'function renderSearchResults(){', 'utf-8'),
    ('#291 batch editor col fixed layout', "table.style.tableLayout='fixed';", 'utf-8'),
    # #292 旧实现用 ev._dragMoved 抑制拖拽后误点（事件块内嵌单格）；#422 改为悬浮段委托选中，视图切换早已移除，故该旧串作废
    ('#292 month seg click selects record (no view switch)', "selectRow(rowIdx); showDetailPanel(rowIdx);", 'utf-8'),
    # #421 旧的自由像素 translate(dx,dy) 拖拽已改为按天/周吸附（daysX*cellW / wk*cellH），见下方 negative_checks 回归守卫
    ('#294 cal-event selected gallery style', 'box-shadow:0 0 0 2px var(--accent);z-index:2;', 'utf-8'),
    ('#295 day view today col no fill empty', '.cal-day-col.today:not(.is-week){}', 'utf-8'),
    # --- v2.9.7 feedback #297~#303 (drag / gantt / detail / batch) ---
    ('#303 gantt quarter range anchor/rolling', 'max:new Date(a.getFullYear(), qm+12, 0, 23,59,59) }', 'utf-8'),
    ('#303 gantt year dim button', "['year','年']", 'utf-8'),
    ('#303 ganttStep year branch', "if(dim==='year') n.setFullYear(n.getFullYear()+1)", 'utf-8'),
    ('#298/#412 month drag row-to-7-days delta', 'daysY=7*((cellH>0)?Math.round(dy/cellH):0)', 'utf-8'),
    ('#298 month drag resize-start clamp', 'if(ne && ns>=ne) ns=new Date(ne.getTime()-86400000)', 'utf-8'),
    ('#298 month drag guard invalid date', '防呆：绝不写入非法日期', 'utf-8'),
    ('#298 day view side-by-side layout fn', 'function layoutDayColumn(body)', 'utf-8'),
    ('#298 day view side-by-side call', 'if(!isWeek) layoutDayColumn(body)', 'utf-8'),
    ('#299 detail time input select reverted', "tSel.value=pad(d.getHours())+':'+pad(d.getMinutes())", 'utf-8'),
    ('#302 batch editor typeSel cell-edit', "typeSel.className='cell-edit'", 'utf-8'),
    ('#302 batch editor opts cell-edit', "optsArea.className='cell-edit'", 'utf-8'),
    # --- v2.9.7 feedback #305~#308 (gantt horizontal scroll / today / year / duration / dashboard total) ---
    ('#305 gantt step anchor helper', 'function ganttStepAnchor(dim, dir)', 'utf-8'),
    ('#305 gantt scroll pane right', 'gantt-scroll', 'utf-8'),
    ('#305 gantt Today button id', "todayBtn.id='ganttToday'", 'utf-8'),
    ('#305 gantt default duration hours param', 'defaultDurationHours', 'utf-8'),
    ('#305 gantt addRow prefill duration', "var dur=(g.defaultDurationHours!=null?g.defaultDurationHours:4)", 'utf-8'),
    # #305 的固定像素画布宽已被 #332 的“日/周/月充满容器宽”取代，见下方 #332 检查项
    ('#345 gantt canvas px all dims', 'var canvasW=Math.round(totalDays*GANTT_DAY_PX)', 'utf-8'),
    ('#307 search locate scrollIntoView', "el.scrollIntoView({block:'nearest', inline:'nearest'})", 'utf-8'),
    ('#307 cal-event selected gallery style', 'box-shadow:0 0 0 2px var(--accent);z-index:2;', 'utf-8'),
    ('#306 blue text selection', '::selection{background:var(--accent);color:#fff;}', 'utf-8'),
    ('#308 dashboard total settings button', '图表设置', 'utf-8'),
    ('#308 dashboard total settings function', 'function showDashboardTotalSettings()', 'utf-8'),
    # #309 / #311 已分别被 #341（固定 1040px 宽）与 #339（绝对像素边缘判定）取代，见下方检查项
    # --- v2.9.7 feedback #320~#321 (form render crash fix + search locate fix) ---
    ('#320 form datetime split wires _timeInput (fixes render crash)', 'wrap._timeInput=tSel;', 'utf-8'),
    ('#321 search locate function', 'function locateInCurrentView(rowIndex){', 'utf-8'),
    ('#321 search locate navigates calendar to task date', 'calState.year=dv.getFullYear(); calState.month=dv.getMonth(); calState.day=dv.getDate();', 'utf-8'),
    ('#321 search locate navigates gantt to task start', 'ganttState.anchorDate=sv', 'utf-8'),
    # --- v2.9.7 feedback #326~#330 (gantt two-pane / checkbox / dashboard / calendar arrows / search scope) ---
    ('#326 dashboard column min-width array', 'DASH_COLS', 'utf-8'),
    ('#327 gantt two-pane body', 'gantt-body', 'utf-8'),
    ('#327 gantt frozen left pane', 'gantt-frozen', 'utf-8'),
    ('#327 gantt scroll pane', 'gantt-scroll', 'utf-8'),
    ('#327 gantt frozen row class', 'gantt-fz-row', 'utf-8'),
    ('#327 gantt group frozen label class', 'gantt-group-fz', 'utf-8'),
    ('#327 gantt vertical scroll sync', 'fzBody.addEventListener', 'utf-8'),
    ('#327 gantt today line 2px (overlay)', '.gantt-overlay .gantt-today-line{position:absolute;top:0;bottom:0;width:2px;background:#F53F3F;box-sizing:border-box;}', 'utf-8'),
    ('#328 checkbox left align rule', '.setting-row input[type=checkbox]{flex:0 0 auto;width:16px;height:16px;margin:0;}', 'utf-8'),
    ('#329 search results only calendar/form', "vt!=='Calendar' && vt!=='Form'", 'utf-8'),
    ('#330 calendar arrows ◀▶', 'id="calPrev">◀', 'utf-8'),
    ('#330 gantt rangeLbl compact (no flex:1)', 'flex:0 0 auto;min-width:0;white-space:nowrap', 'utf-8'),
    ('#330 gantt step anchor by dim (mirrors calendar)', 'function ganttStepAnchor(dim, dir)', 'utf-8'),
    # --- v2.9.8 feedback #331~#343 (dashboard/gantt/calendar/search/settings/batch widths + date BUG) ---
    ('#331 dashboard total settings width 1200', "modal.style.width='1200px'", 'utf-8'),
    ('#331 dashboard title column widened to 220', "DASH_COLS=[['标题',220]", 'utf-8'),
    ('#331 dashboard total settings no horizontal scroll', 'max-height:60vh;overflow-y:auto;overflow-x:hidden;', 'utf-8'),
    ('#331 dashboard table fixed layout percent widths', 'var dashTotalW=DASH_COLS.reduce', 'utf-8'),
    ('#345 gantt all dims px canvas (no fit)', '#345：所有维度', 'utf-8'),
    ('#332 gantt setCanvasWidth helper', 'function setCanvasWidth(el)', 'utf-8'),
    ('#345 gantt horizontal scroll all dims', "scroll.style.overflowX='auto'", 'utf-8'),
    ('#345 gantt day px map', 'var GANTT_DAY_PX={day:80, week:40, month:16, quarter:12, year:4}[dim]||12', 'utf-8'),
    ('#333 gantt range no data-recenter jump', 'var a = anchor ? new Date(anchor.getTime()) : new Date();', 'utf-8'),
    ('#333 gantt quarter rolling 4-quarter window', 'return { min:new Date(a.getFullYear(), qm, 1), max:new Date(a.getFullYear(), qm+12, 0, 23,59,59) };', 'utf-8'),
    ('#333 gantt initial anchor uses data midpoint when today outside', "ganttState.anchorDate=(dataMin&&dataMax&&(t0<dataMin||t0>dataMax))", 'utf-8'),
    ('#334 calendar field-toggle button removed', "if(type!=='Chart' && type!=='Calendar')", 'utf-8'),
    ('#335 app setting calDefaultDurationMinutes', 'calDefaultDurationMinutes:30', 'utf-8'),
    ('#335 calendar duration options list', 'var CAL_DURATION_OPTIONS=[15,30,45,60,120]', 'utf-8'),
    ('#335 calDraftValues helper (start + default duration)', 'function calDraftValues(cfg, baseDate, hour, min)', 'utf-8'),
    ('#335 calendar settings duration select', "durSel.id='calDefaultDuration'", 'utf-8'),
    ('#335 addRow calendar branch uses default duration', "if(activeViewType()==='Calendar'){", 'utf-8'),
    ('#336 month view weekday names 周一..周日', "var base=['周日','周一','周二','周三','周四','周五','周六'];", 'utf-8'),
    ('#336 month view header uses weekDayNames()', 'weekDayNames().forEach(function(d){', 'utf-8'),
    ('#336 cal-dow matches week column head format', '.cal-dow{background:var(--bg-2);text-align:center;height:30px;line-height:30px;font-weight:600;font-size:12px;', 'utf-8'),
    ('#337 global settings default factory', 'function defaultAppSettings()', 'utf-8'),
    ('#337 global settings persisted note', '以上为软件设置，保存后与具体文件无关', 'utf-8'),
    ('#338 search hit text helper', 'function searchHitText(row, kw)', 'utf-8'),
    ('#338 search results join with full-width semicolon', "out.join('；')", 'utf-8'),
    ('#338 search results use unified formatter', 'item.textContent=searchHitText(r, f);', 'utf-8'),
    # #421 ⟨⟩ 握把已改为白色双竖纹 ::before，且手柄类名去掉 .cal-event-resize 基类（不再与日视图纵向条冲突），见 negative_checks
    ('#339/#356/#412 month resize-end shifts end by day delta', 'ne=new Date(origEnd.getTime()+dd*86400000);', 'utf-8'),
    ('#339 month cell carries date for drop targeting', 'cell.dataset.date=fmtDate(c.date);', 'utf-8'),
    # #421 旧 resize 手柄带 .cal-event-resize 基类（撑成全宽蓝条）已移除，见 negative_checks
    ('#340 settings panel is now a rounded modal', "ov.id='appSettingsOverlay'", 'utf-8'),
    ('#340 settings modal head title', '<span>软件设置</span>', 'utf-8'),
    ('#341 batch editor width 1040', "modal.style.width='1200px'", 'utf-8'),
    ('#341 batch editor column widths', "BATCH_COLS=[['字段名',130],['必填',48],['类型',124],['步进值',84],['最大值',84],['最小值',84],['显示格式',120],['最小长度',84],['最大长度',84],['正则验证',120],['错误提示',120],['选项（每行一个）',126]]", 'utf-8'),
    ('#342 app setting weekStartDay', "weekStartDay:'mon'", 'utf-8'),
    ('#342 weekStartIndex helper', 'function weekStartIndex()', 'utf-8'),
    ('#342 weekCol helper follows week start', 'function weekColOf(dateOrDow)', 'utf-8'),
    ('#342 month first column follows week start', 'var startDow=weekColOf(first);', 'utf-8'),
    ('#342 calendar settings week start select', "wsSel.id='calWeekStart'", 'utf-8'),
    ('#342 week view head derives from actual date', "['周日','周一','周二','周三','周四','周五','周六'][d.getDay()]", 'utf-8'),
    ('#343 gantt bad-row text helper', 'function ganttBadRowsText(bad)', 'utf-8'),
    ('#343 gantt same-day start/end is valid', 'if(e.getTime()<s.getTime()){ badRows.push', 'utf-8'),
    ('#343 gantt red error bar', 'view-err-bar', 'utf-8'),
    ('#343 error bar css', '.view-err-bar{flex:0 0 auto;background:#FFECE8;', 'utf-8'),
    ('#343 calendar bad-row detection', 'var calBad=[];', 'utf-8'),
    # --- v2.9.8 第六批反馈 #344~#349（批量编辑增强 / 甘特全维度滚动 / 设置改名迁移 / 日期误保存 / 月视图拖拽） ---
    ('#344 batch editor new cols format/len/regex/err', "['显示格式',120],['最小长度',84],['最大长度',84],['正则验证',120],['错误提示',120]", 'utf-8'),
    ('#346 月视图最大任务数迁入日历设置', '月视图最大任务数', 'utf-8'),
    ('#347 图表标签阈值控件迁入仪表盘工具条', '隐藏≤', 'utf-8'),
    ('#348 表格日期列规范比较避免误保存', 'function cellValueEqual', 'utf-8'),
    ('#349 月视图拖拽落点穿透定位修复', "state._calDragMoved=moved; // #349 拖拽结束后抑制本次落点格/段的单击", 'utf-8'),
    ('#349/#412 month drag end-after-start clamp', 'if(ne<=ns) ne=new Date(ns.getTime()+86400000);', 'utf-8'),
    # --- v2.9.8 第七批反馈 #350（甘特图表区独立横向平移 / 底部滚动条 / 视口保留） ---
    ('#350 gantt scrollTotal buffered+aligned range', 'function ganttScrollTotal(dim, dataMin, dataMax)', 'utf-8'),
    ('#350 gantt floorToTick natural alignment', 'function floorToTick(d, dim)', 'utf-8'),
    ('#350 gantt ceilToTick natural alignment', 'function ceilToTick(d, dim)', 'utf-8'),
    ('#350 gantt no-task default window ±6 months', 'new Date(t.getFullYear(), t.getMonth()-6, 1)', 'utf-8'),
    ('#350 gantt custom bottom scrollbar class', "hscroll.className='gantt-hscroll'", 'utf-8'),
    ('#350 gantt bottom scrollbar thumb class', "hthumb.className='gantt-hscroll-thumb'", 'utf-8'),
    ('#350 gantt center on date (viewport pan only)', 'function ganttCenterOnDate(d)', 'utf-8'),
    ('#350 gantt preserve viewport on dim switch', 'function ganttSwitchDim(d)', 'utf-8'),
    ('#350 gantt live range label on scroll', 'function ganttUpdateRangeLabel()', 'utf-8'),
    ('#350 gantt canvas drag-to-pan', 'startLeft-(ev.clientX-startX)', 'utf-8'),
    ('#350 gantt prev/next page buttons', 'ganttScrollEl.scrollLeft-ganttScrollEl.clientWidth', 'utf-8'),
    ('#350 gantt hide native scrollbar css', '.gantt-scroll{flex:1;min-width:0;overflow:auto;position:relative;background:var(--bg);scrollbar-width:none;}', 'utf-8'),
    ('#350 gantt hide native scrollbar webkit', '.gantt-scroll::-webkit-scrollbar{width:0;height:0;display:none;}', 'utf-8'),
    # --- v2.9.9 第八批反馈 #352-#357 ---
    ('#352 gantt day tick shows weekday label', "'周'+['日','一','二','三','四','五','六'][t.getDay()]", 'utf-8'),
    ('#352 gantt day step = +1 day (no hourly cram)', "n.setDate(n.getDate()+1); // #352", 'utf-8'),
    ('#353 batch editor type column widened to 124', "['类型',124]", 'utf-8'),
    ('#354 percentage step honors field config', "(f.step!=null && f.step>0)?String(f.step):'1'; // #354", 'utf-8'),
    ('#354 number step honors field config', "(f.step!=null && f.step>0)?String(f.step):((t==='Integer')?'1':'0.01')", 'utf-8'),
    ('#354 step persisted in applyFieldOverrides', "if(o.step!=null) r.step=o.step; return r; }); // #354", 'utf-8'),
    ('#354 step written back in getFieldOverride', "step:f.step}:null; // #354", 'utf-8'),
    ('#354 step synced to override config', "ov.step=f.step; ov.userDefined=true; // #354", 'utf-8'),
    ('#355 current-line unified 2px (calendar)', ".cal-current-line{position:absolute;height:2px;background:#F53F3F;z-index:5;pointer-events:none;box-sizing:border-box;}", 'utf-8'),
    # #421 旧左缘手柄带 .cal-event-resize 基类已移除，见 negative_checks
    # #421 旧右缘手柄带 .cal-event-resize 基类已移除，见 negative_checks
    ('#356 month resize uses delegated monthSegMouseDown (mode from edge detect)', "monthSegMouseDown(seg, r, cfg, mode, e, {grid:grid, cells:cells, cellEls:cellEls});", 'utf-8'),
    ('#356 monthSegMouseDown refactor', "function monthSegMouseDown(seg, r, cfg, mode, e, ctx){", 'utf-8'),
    ('#357 gantt boundary mode project', "var mode=(cfg.boundaryMode||'feishu');", 'utf-8'),
    ('#357 gantt project expand lower bound', "lo=new Date(dataMin.getTime()-expandDays*86400000);", 'utf-8'),
    ('#357 gantt project expand upper bound', "hi=new Date(dataMax.getTime()+expandDays*86400000);", 'utf-8'),
    ('#357 gantt boundary UI option', "'项目边界外扩天数','project'", 'utf-8'),
    ('#357 gantt boundary saved to config', "v.ganttConfig.boundaryMode=bndSel.value; v.ganttConfig.boundaryExpandDays=", 'utf-8'),
    # --- v2.9.7 第十批反馈 #359~#366 ---
    ('#359 chart card tools setting default', 'showChartCardTools:true', 'utf-8'),
    ('#359 chart card tools UI checkbox', '图表控制开关', 'utf-8'),
    ('#359 chart view buttons gated', "if(APP_SETTINGS.showChartCardTools!==false){", 'utf-8'),
    ('#360 WebView2 context menu disabled (HtmlMainForm)', 'AreDefaultContextMenusEnabled', 'utf-8'),
    ('#360 WebView2 context menu disabled (TaskPane)', 'AreDefaultContextMenusEnabled', 'utf-8'),
    ('#361 chart settings modal label threshold', "thInp.id='setLabelThresholdModal'", 'utf-8'),
    ('#361 chart settings modal threshold label text', '隐藏≤该值的图表标签', 'utf-8'),
    ('#362 week start any day array', "WEEK_START_DAYS=['sun','mon','tue','wed','thu','fri','sat']", 'utf-8'),
    ('#362 week start labels', "WS_LABELS={sun:'周日',mon:'周一',tue:'周二',wed:'周三',thu:'周四',fri:'周五',sat:'周六'}", 'utf-8'),
    ('#362 week start index dynamic', 'WEEK_START_DAYS.indexOf(APP_SETTINGS.weekStartDay)', 'utf-8'),
    ('#363 dashboard export context menu function', 'function showDashboardExportMenu(e)', 'utf-8'),
    ('#363 dashboard export PNG call', "api.call('exportDashboard',{format:'png',clipboard:false,x:crop.x,y:crop.y,w:crop.w,h:crop.h})", 'utf-8'),
    ('#363 dashboard export clipboard call', "api.call('exportDashboard',{format:'png',clipboard:true,x:crop.x,y:crop.y,w:crop.w,h:crop.h})", 'utf-8'),
    ('#363 C# exportDashboard dispatch case', 'exportDashboard', 'utf-16le'),
    ('#363 C# ExportDashboard method', 'ExportDashboard', 'utf-8'),
    ('#363 C# NotifyToast method', 'NotifyToast', 'utf-16le'),
    ('#364 line chart bottom axis removed comment', '#364：折线/面积图去掉底部横线', 'utf-8'),
    ('#364 line chart axis gated by type', "if(cfg.type!=='Line' && cfg.type!=='Area'){", 'utf-8'),
    ('#366 FieldOverride Step property (C#)', 'Step', 'utf-8'),
    ('#366 FieldFilterConfig class (C#)', 'FieldFilterConfig', 'utf-8'),
    ('#366 ViewConfig FieldFilter property (C#)', 'FieldFilter', 'utf-8'),
    ('#366 JS restoreViewState helper', 'function restoreViewState(v)', 'utf-8'),
    ('#366 JS save filter to view config', 'av.filter=state.filter', 'utf-8'),
    ('#366 JS save fieldFilter to view config', 'av.fieldFilter=state.fieldFilter', 'utf-8'),
    ('#366 per-view summary position UI', "spSel.appendChild(new Option('数据末尾（默认）','DataEnd'))", 'utf-8'),
    ('#366 per-view summary position applied', 'v.summaryPosition=spSel.value', 'utf-8'),
    ('#366 summaryPosition no longer reads APP_SETTINGS', '不再读取全局软件设置', 'utf-8'),
    ('#367 dashboard top label-threshold control removed (kept in chart settings modal)', "thInp.id='setLabelThresholdModal'", 'utf-8'),
    ('#368 export crop helper', 'function getExportCrop()', 'utf-8'),
    ('#368 export passes crop coords to C#', "x:crop.x,y:crop.y,w:crop.w,h:crop.h", 'utf-8'),
    ('#368/#375 C# crop comment renamed', '已复制图表到剪贴板', 'utf-16le'),
    ('#375 export menu label renamed', '图表导出图片（PNG）', 'utf-8'),
    ('#375 clipboard label renamed', '图表复制到剪贴板', 'utf-8'),
    ('#375 export crop uses scrollWidth/scrollHeight', 'inner.scrollWidth', 'utf-8'),
    ('#375/#379 export crop left/top inset 10', 'var LEFT=10, TOP=10', 'utf-8'),
    ('#379 export crop bottom = last chart bottom + 10', "querySelectorAll('.chart-box')", 'utf-8'),
    ('#379 export crop bottom adds 10px', 'Math.round(bottomY)+10', 'utf-8'),
    ('#378 KPI card settings gated by chart switch', "showChartCardTools!==false){ headHtml+=", 'utf-8'),
    ('#379 full-page capture via CDP captureBeyondViewport', 'captureBeyondViewport', 'utf-16le'),
    ('#379 C# calls CDP Page.captureScreenshot', 'Page.captureScreenshot', 'utf-16le'),
    ('#379 JS unlock dashboard for full capture', '__unlockDash', 'utf-8'),
    ('#379 JS relock dashboard after capture', '__relockDash', 'utf-8'),
    ('#370 monthMaxEvents moved to software settings window', "cbMonth.id='setMonthMaxApp'", 'utf-8'),
    ('#370 monthMaxEvents still in APP_SETTINGS default', 'monthMaxEvents:5', 'utf-8'),
    # --- v2.9.12 / DateHelpFix (#386/#387/#388/#389) ---
    ('#386/#382 DatePickerStyles.xaml embedded resource', 'Resources/DatePickerStyles.xaml', 'utf-16le'),
    ('#386 MultiTableDatePicker subclass (DatePicker fix)', 'MultiTableDatePicker', 'utf-8'),
    ('#386 VisualTreeHelperEx helper', 'VisualTreeHelperEx', 'utf-8'),
    ('#386 CalendarDayButton light-blue style key', 'MultiTableCalendarDayButtonStyle', 'utf-8'),
    ('#386 selected day light blue #B3E5FC', '#B3E5FC', 'utf-8'),
    ('#386 wheel flips 2 months per notch (WheelMonthsPerNotch)', 'WheelMonthsPerNotch', 'utf-8'),
    ('#387 help modal enlarged width', 'min(780px, 94vw)', 'utf-8'),
    ('#387 help text comfortable font 15px', 'font-size:15px', 'utf-8'),
    ('#389 help button appended after refresh in sidebar', 'top.appendChild(helpBtn)', 'utf-8'),
    ('#383 help icon added to ICONS', "path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0 M12 17l0 .01 M12 13.5a1.5 1.5 0 0 1 1 -1.5a2.6 2.6 0 1 0 -3 -4\"", 'utf-8'),
    ('#383 showHelp function', 'function showHelp()', 'utf-8'),
    ('#383 help panel copy button', '复制全部', 'utf-8'),
    ('#383 HELP_TEXT calendar start/end datetime emphasis', '日历视图（重点：开始/结束日期与时间）', 'utf-8'),
    ('#383 HELP_TEXT gantt start/end emphasis', '甘特视图（重点：开始/结束日期）', 'utf-8'),
    ('#383 About dialog links to help', '点击「帮助」查看各视图说明', 'utf-8'),
    ('#384 quick-start TXT help document title string in HELP_TEXT', '普通用户快速使用帮助', 'utf-8'),
    # --- v2.9.17 / GalleryHtFix3 (#397 画册卡片去掉 min-height 硬下限/内容自然撑高 + 底部留白-15px + 网格 grid-auto-rows 防重叠) ---
    ('#391 custom HTML date picker attachDatePicker', 'function attachDatePicker', 'utf-8'),
    ('#391 date input switched to text + readonly picker', "input.type='text'; input.readOnly=true;", 'utf-8'),
    ('#391 selected day light blue #B3E5FC (HTML popup)', '#B3E5FC', 'utf-8'),
    ('#391 wheel flips 1 month per notch (HTML popup)', 'moveMonth(disp, dir)', 'utf-8'),
    ('#391 today button in date picker', '今天', 'utf-8'),
    ('#391 datetime split input uses text + picker', 'attachDatePicker(dInp, {withTime:false})', 'utf-8'),
    ('#391 datetime field uses picker with time', 'attachDatePicker(input, {withTime:true})', 'utf-8'),
    ('#392 gallery image base64 loader setImgSrc', 'function setImgSrc', 'utf-8'),
    ('#392 gallery renders via getImageBase64 API', "api.call('getImageBase64'", 'utf-8'),
    ('#397 gallery grid auto-rows min-content (anti-overlap)', 'grid-auto-rows:min-content;', 'utf-8'),
    ('#397 with-img card min-height removed (content-driven height)', '.gallery-card.with-img .gbody{padding-bottom:7px;}', 'utf-8'),
    ('#394 date picker weekend light blue #E8F2FC', 'E8F2FC', 'utf-8'),
    ('#394 date picker week start follows global setting', 'var startDow = weekStartIndex();', 'utf-8'),
    ('#394 date picker title year+month two lines', ' 年<br>', 'utf-8'),
    ('#395 gallery imgShow gating (image off hides area)', 'var imgShow = folderMode || !!imgField;', 'utf-8'),
    ('#395 gallery with-img class on card', "imgShow?' with-img':'')", 'utf-8'),
    ('#395 gallery match field label renamed', '图片匹配字段', 'utf-8'),
    ('#392 gallery image area height 120px flex-shrink (-20px)', '.gallery-card .gimg{height:120px;flex-shrink:0;width:100%;', 'utf-8'),
    ('#392 gallery img fills container', '.gallery-card .gimg img{width:100%;height:100%;object-fit:cover;}', 'utf-8'),
    ('#392 C# getImageBase64 api keyword (utf-16le)', 'getImageBase64', 'utf-16le'),
    ('#392 C# GetImageBase64 method (utf-8)', 'GetImageBase64', 'utf-8'),
    ('#396 gallery fields follow table left-to-right order', 'state.fields.filter(function(f){ return state.visibleFields.indexOf(f.name)>=0 && f.name!==imgField && f.name!==titleField; }', 'utf-8'),
    ('#397 with-img card bottom padding 7px (was 22px, -15px whitespace)', '.gallery-card.with-img .gbody{padding-bottom:7px;}', 'utf-8'),
    ('#396 gallery grid align-items:start (no row-stretch)', 'align-content:start;align-items:start;', 'utf-8'),
    ('#397 gallery card gap 10px (was 14px)', 'gap:10px;', 'utf-8'),
    # --- v2.9.18 / GalleryCircleGanttSave (#400 画册圆形图片显示模式 + #402 甘特拖拽调整+保存模式开关) ---
    ('#400 gallery circle css (centered circular crop)', '.gallery-card .gimg.circle{width:104px;height:104px;border-radius:50%;margin:10px auto 0;', 'utf-8'),
    ('#400 gallery circle img border-radius', '.gallery-card .gimg.circle img{border-radius:50%;}', 'utf-8'),
    ('#400 gallery imageShape select option 圆形（居中裁剪）', '圆形（居中裁剪）', 'utf-8'),
    ('#400 gallery imageShape applied to cardMeta', 'v.cardMeta.imageShape=shapeSel.value', 'utf-8'),
    ('#400 gallery render applies circle class', "(cfg.cardMeta&&cfg.cardMeta.imageShape)==='circle'", 'utf-8'),
    ('#402 ganttSaveMode default in app settings', "ganttSaveMode:'auto'", 'utf-8'),
    ('#402 ganttSaveMode loaded from localStorage', "o.ganttSaveMode==='auto'||o.ganttSaveMode==='manual'", 'utf-8'),
    ('#402 gantt save mode UI label', '可视化调整保存模式', 'utf-8'),
    ('#402 manual mode branch in makeGanttBarDraggable', "if(APP_SETTINGS.ganttSaveMode==='manual'){", 'utf-8'),
    ('#402 markGanttDirty function', 'function markGanttDirty', 'utf-8'),
    ('#402 flushGanttEdits function', 'function flushGanttEdits', 'utf-8'),
    ('#402 showGanttSaveBar function', 'function showGanttSaveBar', 'utf-8'),
    ('#402 guardUnsavedVisualEdits function', 'function guardUnsavedVisualEdits', 'utf-8'),
    ('#402 gantt-save-bar css', '.gantt-save-bar{position:fixed;right:16px;bottom:16px;', 'utf-8'),
    ('#402 window.__mtFlushVisualEdits global', 'window.__mtFlushVisualEdits=function(){ return flushGanttEdits(); }', 'utf-8'),
    ('#402 C# setVisualEditDirty dispatch (utf-16le)', 'setVisualEditDirty', 'utf-16le'),
    # --- v2.9.19 甘特交互优化（#406 软件风格保存确认弹窗 / #407 两端调整手柄 / #408 拖动后保持视图 / #409 行高控制）---
    ('#406 close confirm routed to HTML modal (no WinForms MessageBox)', 'window.__mtPromptVisualEditClose=function(){', 'utf-8'),
    ('#406 C# resolveVisualEditClose dispatch (utf-16le)', 'resolveVisualEditClose', 'utf-16le'),
    ('#406 discard bridge global', 'window.__mtDiscardVisualEdits=function(){ discardGanttEdits(); }', 'utf-8'),
    ('#406 simplified confirm text 是否保存', '有未保存的甘特图调整，是否保存？', 'utf-8'),
    ('#407 left resize mode in makeGanttBarDraggable', "mode = (x<=RESIZE_EDGE) ? 'resize-l' : (x>=rect.width-RESIZE_EDGE ? 'resize-r' : 'move')", 'utf-8'),
    ('#407 right resize handle element', "className='gantt-resize gantt-resize-r'", 'utf-8'),
    ('#407 resize handle css', '.gantt-resize{position:absolute;top:0;bottom:0;width:10px;', 'utf-8'),
    ('#408 drag no longer re-renders whole gantt (keeps scroll)', 'function ganttCenterBarIfNeeded', 'utf-8'),
    ('#408 center-only-when-out-of-view guard', 'if(within) return;', 'utf-8'),
    ('#409 row-height css variable on gantt-row', 'height:var(--gantt-row-h,30px)', 'utf-8'),
    ('#409 row-height applied from cfg.rowHeight', "{'compact':30,'normal':44,'loose':58}[ (cfg.rowHeight)||'compact' ]", 'utf-8'),
    ('#409 row-height select in gantt settings', "grhSel.appendChild(new Option('宽松','loose'));", 'utf-8'),
    # --- v2.9.20 甘特行高可见 + 日历拖拽重写 + 日历行高（#411 行高进 showGanttSettings / #412 月视图拖拽像素→天 / #413 日历行加高）---
    ('#411 row-height control now in showGanttSettings', 'v.ganttConfig.rowHeight=grhSel.value; // #409 行高控制', 'utf-8'),
    ('#412 month drag pixel-to-day conversion', 'daysX=(cellW>0)?Math.round(dx/cellW)', 'utf-8'),
    ('#412 month drag pixel-to-day comment', "var deltaDays=daysX+daysY;", 'utf-8'),
    ('#412 month drag edge-detection resize mode', 'e.clientX-rect.left<=RESIZE_EDGE', 'utf-8'),
    ('#413 calendar grid row adaptive (fr weights set in JS for self-height)', 'repeat(6,minmax(28px,1fr))', 'utf-8'),
    # --- v2.9.21 甘特行高顶部快捷切换（#415）+ 月视图横向拉伸可用化（#416）---
    ('#415 gantt row-height quick switch helper', 'function applyGanttRowHeight(val){', 'utf-8'),
    ('#416 calEndField auto-detects end date field', 'function calEndField(cfg){', 'utf-8'),
    ('#416 month drag uses effective end field', 'var effEnd=calEndField(cfg);', 'utf-8'),
    ('#416 month drag resize outline feedback', "if(mode==='move'){", 'utf-8'),
    ('#416 month drag end date uses effEnd', 'updates.push({field:effEnd, value:isDtE?fmtDateTimeLocal(ne,eh,emm):fmtDate(ne)});', 'utf-8'),
    # --- v2.9.22 甘特行高改单按钮弹出菜单（#417）+ 月视图甘特式左右控件（#418）---
    ('#417 gantt row-height single button opens popup menu', 'function showGanttRowHeightMenu(anchor){', 'utf-8'),
    ('#417 toolbar shows single 行高 button', "rhBtn.textContent='行高';", 'utf-8'),
    ('#418 month drag edge-detects on event block like gantt', "mode=(e.clientX-rect.left<=RESIZE_EDGE)?'resize-start':((rect.right-e.clientX<=RESIZE_EDGE)?'resize-end':'move')", 'utf-8'),
    ('#418 month drag RESIZE_EDGE=12 on block', 'var RESIZE_EDGE=12;', 'utf-8'),
    ('#418 month drag left-edge = resize-start', "(e.clientX-rect.left<=RESIZE_EDGE)?'resize-start'", 'utf-8'),
    ('#418 month handle has ew-resize grab cursor', 'cursor:ew-resize;user-select:none;', 'utf-8'),
    ('#418 single-date fallback: right edge adjusts anchor field', "else if(mode==='resize-end'){", 'utf-8'),
    # --- v2.9.23 月视图手柄常显可抓（#419，仿甘特条）---
    ('#419 month handles now always visible & grabbable (ew-resize, opacity .92)', '.cal-event-seg .cal-event-resize-l,.cal-event-seg .cal-event-resize-r{position:absolute;top:0;bottom:0;width:12px;', 'utf-8'),
    ('#419 month handles bind resize-start mousedown', "var hl=document.createElement('div'); hl.className='cal-event-resize-l'; seg.appendChild(hl);", 'utf-8'),
    ('#419 month handles bind resize-end mousedown', "var hr=document.createElement('div'); hr.className='cal-event-resize-r'; seg.appendChild(hr);", 'utf-8'),
    # --- v2.9.25 月视图手柄修复（#421）：去类名冲突 + 方向中性握把 + 按天吸附 ---
    ('#421 month handle class no longer collides with day-view .cal-event-resize', "hl.className='cal-event-resize-l';", 'utf-8'),
    ('#421 month handle right class no collision', "hr.className='cal-event-resize-r';", 'utf-8'),
    ('#421 month handle neutral grip (no unicode arrow)', ".cal-event-seg .cal-event-resize-l::before,.cal-event-seg .cal-event-resize-r::before{content:'';width:2px;", 'utf-8'),
    ('#421 drag guard uses closest handle selector', "e.target.closest('.cal-event-resize-l')", 'utf-8'),
    ('#421 drag snaps horizontally by day cell width', "var daysX=(cellW>0)?Math.round(dx/cellW):0;", 'utf-8'),
    ('#421 drag snaps vertically by whole week', "var wk=(cellH>0)?Math.round(dy/cellH):0;", 'utf-8'),
    # --- v2.9.26 月视图事件悬浮分段（#422）：事件绝对定位覆盖方格之上，按周分段+泳道堆叠，拖拽实时重排 ---
    ('#422 month events float above cells (absolute seg layer)', ".cal-event-seg{position:absolute;height:18px;line-height:18px;", 'utf-8'),
    ('#422 dragging seg opacity feedback', ".cal-event-seg.dragging{opacity:.85;z-index:50;}", 'utf-8'),
    ('#422 event layout helper (lane + week-band segmentation)', "function layoutMonthEvents(grid, cells, cellEls, cfg){", 'utf-8'),
    ('#422 per-seg maker (first/last handle flags)', "function makeMonthSeg(grid, cellEls, r, cfg, startIdx, endIdx, lane, isFirst, isLast){", 'utf-8'),
    ('#422 drag relayout gives live multi-day length', "relayoutEvent(ctx.grid, ctx.cellEls, ctx.cells, r, cfg, nd.ns, nd.ne, lane);", 'utf-8'),
    ('#422 drag handler (renamed from monthDragStart)', "function monthSegMouseDown(seg, r, cfg, mode, e, ctx){", 'utf-8'),
    ('#422 date->cell-index helper', "function cellIndexForDate(cells, date){", 'utf-8'),
    ('#422 resize-start handle only on first seg', "if(isFirst){ var hl=document.createElement('div'); hl.className='cal-event-resize-l'; seg.appendChild(hl); }", 'utf-8'),
    ('#422 resize-end handle only on last seg', "if(isLast){ var hr=document.createElement('div'); hr.className='cal-event-resize-r'; seg.appendChild(hr); }", 'utf-8'),
    ('#422 drag delegated from grid', "monthSegMouseDown(seg, r, cfg, mode, e, {grid:grid, cells:cells, cellEls:cellEls});", 'utf-8'),
    # --- v2.9.27 月视图重叠布局（#423）：动态泳道(区间图着色=最大团) + 行高按比例自适应 + 3px间隔 + 极端密度「+N更多」兜底 ---
    ('#423 dynamic lane constants (18px row + 3px gap + 28px top reserve + 30px min cell)', "var MT_LANEH=18, MT_LANEGAP=3, MT_PADX=3, MT_PADTOP=28, MT_CELLMIN=30, MT_DRAGGING=false;", 'utf-8'),
    ('#423 dynamic lane cap configurable via APP_SETTINGS.monthMaxEvents (default 8)', "var MT_MAXLANES=(APP_SETTINGS.monthMaxEvents && APP_SETTINGS.monthMaxEvents>0)?APP_SETTINGS.monthMaxEvents:8;", 'utf-8'),
    ('#423 interval-graph coloring by start order (greedy max-clique lanes)', "events.sort(function(a,b){ return a.sIdx-b.sIdx || a.eIdx-b.eIdx; });", 'utf-8'),
    ('#423 lane-free test across all touched bands (cross-band lane lock)', "function laneFreeInBands(lane, bands){", 'utf-8'),
    ('#426-4 per-band lane compaction map (eliminates blank lanes between events)', "var laneMap=[[],[],[],[],[],[]];", 'utf-8'),
    ('#422 seg top = cell.offsetTop + MT_PADTOP + lane*(LANEH+GAP)', "var left=c0.offsetLeft+MT_PADX, top=c0.offsetTop+MT_PADTOP+lane*(MT_LANEH+MT_LANEGAP);", 'utf-8'),
    ('#427-1 events collected without multi flag (unified system, no top strip)', "events.push({r:r, sIdx:sIdx, eIdx:eIdx, bands:bands});", 'utf-8'),
    ('#428-2 row height from rowSpecs (expanded week -> px fit-all-lanes, others 1fr)', "grid.style.gridTemplateRows=rowSpecs.join(' ');", 'utf-8'),
    ('#427-4 K = floor((rowH - PADTOP - 4)/(LANEH+GAP)) per-week capacity', "var K = rowH>0 ? Math.max(1, Math.floor((rowH - MT_PADTOP - 4)/(MT_LANEH+MT_LANEGAP))) : MT_MAXLANES;", 'utf-8'),
    ('#427-1 render uses compacted lane cl (no blank rows, solo week -> lane 0)', "makeMonthSeg(grid, cellEls, ev.r, cfg, bd[0], bd[1], cl, bd[0]===ev.sIdx, bd[1]===ev.eIdx);", 'utf-8'),
    ('#464 weekend columns fill #F7F7F7 (month view, replaces #D4D4D4)', ".cal-cell.weekend{background:#F7F7F7;}", 'utf-8'),
    ('#423 extreme-density +N-more badge element', "more.className='cal-month-more';", 'utf-8'),
    ('#423 +N-more badge positioned top-right (no overlap with events/date number)', "more.style.top=(lc.offsetTop+2)+'px';", 'utf-8'),
    ('#423 +N-more badge short label (just +N, full text in title)', "more.textContent='+'+cnt;", 'utf-8'),
    ('#424-2 per-band overflow segments hidden (not global)', "if(hiddenByBand[b] && hiddenByBand[b][ev.r.rowIndex]) return;", 'utf-8'),
    # --- v2.9.28 月视图选中/导航修复（#424）：选中高亮覆盖悬浮段 + 按 band 隐藏 + 空周压缩 + 切换视图定位 ---
    ('#424-1 selectRow removes .cal-event-seg.selected highlight', ".cal-event-seg.selected,.gantt-row.selected", 'utf-8'),
    ('#424-1 selectRow adds .cal-event-seg[data-row] highlight (all segs of event)', ".cal-event-seg[data-row=\"'+rowIndex+'\"],.gantt-row[data-row", 'utf-8'),
    ('#424-2 per-band hidden map + moreCountByBand', "var hiddenByBand={};", 'utf-8'),
    ('#428-2 fold only for non-expanded weeks (expanded week shows all lanes)', "if(!MT_EXPANDED[b] && laneCount[b]>K){", 'utf-8'),
    ('#426-4 render uses compacted lane (no blank rows between events)', "var cl=laneMap[b][ev.lane]; if(cl===undefined) return;", 'utf-8'),
    ('#426-3 MT_MAXLANES read live inside layoutMonthEvents (settings change takes effect)', "var MT_MAXLANES=(APP_SETTINGS.monthMaxEvents && APP_SETTINGS.monthMaxEvents>0)?APP_SETTINGS.monthMaxEvents:8;", 'utf-8'),
    ('#426-1 weekend columns get .weekend tint class (getDay 0/6, independent of first column)', "((wd===0||wd===6)?' weekend':'')", 'utf-8'),
    ('#427-6 gallery buildCard extracted (shared by grouped/ungrouped)', "function buildCard(r){", 'utf-8'),
    ('#NEW layoutMonthEvents idempotent: clears prior segs/badges before re-layout', "var prev=grid.querySelectorAll('.cal-event-seg, .cal-month-more');", 'utf-8'),
    ('#427-6 gallery grouping aggregation by displayText', "var groups={}; getVisibleRows().forEach(function(r){ var k=displayText(groupBy,r)||'（空）';", 'utf-8'),
    ('#426-2 calendar grid white bg + cell borders (no gray gap leak) + align-content:start (no header stretch)', "align-content:start;min-height:0;", 'utf-8'),
    ('#426-5 gallery grouping dropdown enabled (with 不分组 default option)', "groupSel.appendChild(new Option('不分组',''));", 'utf-8'),
    ('#426-5 renderGalleryInner reads groupBy for grouping', "var groupBy=v?viewGroupField(v):'';", 'utf-8'),
    ('#425 MT_PADTOP=28 reserves top strip so events never cover date numbers', "var MT_LANEH=18, MT_LANEGAP=3, MT_PADX=3, MT_PADTOP=28, MT_CELLMIN=30, MT_DRAGGING=false;", 'utf-8'),
    ('#424-5 month seg label padding clears drag handles (0 14px)', ".cal-event-seg{position:absolute;height:18px;line-height:18px;background:var(--accent-weak);color:var(--accent);border-radius:3px;padding:0 14px;", 'utf-8'),
    ('#424-4 scrollSelectedIntoView scrolls selected element in current view', "function scrollSelectedIntoView(){", 'utf-8'),
    ('#424-4 findRowElByIndex matches data-row (number OR JSON, e.g. table view)', "function findRowElByIndex(sel){", 'utf-8'),
    ('#424-4 renderContent scrolls to selection on view switch', "if(viewChanged && state.selectedRow>0){", 'utf-8'),
    ('#424-4 locateInCurrentView Calendar selector covers .cal-event-seg', ".cal-event-seg[data-row=\"'+rowIndex+'\"],.cal-day-event[data-row", 'utf-8'),
    # --- v2.9.24 月视图手柄可视化 + 实时反馈（#420，与甘特条同原理）---
    ('#420 month handles solid accent bar (gantt-like, white grip)', "background:var(--accent);cursor:ew-resize;user-select:none;z-index:6;opacity:.92;", 'utf-8'),
    ('#420 cal-event padding clears handles', 'padding:1px 14px;', 'utf-8'),
    ('#420 drag live tooltip element', "tip.className='cal-drag-tip';", 'utf-8'),
    ('#420 drag live tooltip shows projected dates', "tip.textContent=tipText(nd);", 'utf-8'),
    ('#420 drag feedback glow on block', "if(MT_DRAGGING) seg.classList.add('dragging');", 'utf-8'),
    # --- v2.9.35 / #428 画册分组改看板布局 + 月视图+N展开该周 + 周末#D4D4D4 + 卡片高度统一 + 配置合并/嵌入/记忆 ---
    ('#428-1 gallery grouped uses kanban horizontal columns layout', "host.className='kanban-cols';", 'utf-8'),
    ('#428-1 gallery group column reuses kanban-col class', "grp.className='kanban-col gallery-group-col';", 'utf-8'),
    ('#428-2 month +N click expands that week (band row grows to fit all lanes, button disappears)', "MT_EXPANDED[band]=true; layoutMonthEvents(grid, cells, cellEls, cfg);", 'utf-8'),
    ('#428-2 month +N title hints expand-the-week', "more.title=cnt+' 项未显示，点击展开该周';", 'utf-8'),
    ('#428-2 MT_EXPANDED state + last-month-key reset', "var MT_EXPANDED={}, MT_LAST_MONTH_KEY='';", 'utf-8'),
    ('#464 weekend fill #F7F7F7 in week view column too', ".cal-day-col.weekend{background:#F7F7F7;}", 'utf-8'),
    ('#428-6 week view weekend class applied by getDay 0/6', "((d.getDay()===0||d.getDay()===6)?' weekend':'')", 'utf-8'),
    ('#428-5 empty field rendered as light placeholder to keep card height uniform', "val===''?'—':escapeHtml(val)", 'utf-8'),
    ('#428-5 empty value placeholder css', ".kanban-card .kfld .v.v-empty,.gallery-card .gfld .v.v-empty{color:var(--text-3);opacity:.6;}", 'utf-8'),
    ('#428-3/#458 merged config auto-restores last table (JS bootstrap)', "var last = lastTable ? state.tables.find(function(t){return t.table===lastTable;}) : null;", 'utf-8'),
    ('#428-4/#459 config embedded into Excel hidden sheet _MultiTableConfig (C# const)', '_MultiTableConfig', 'utf-16le'),
    # --- v2.9.36 / #461 画册分组统一高度(kanban-wrap 包裹) + #462 配置保存位置开关 + #464 周末色#F7F7F7 ---
    ('#461 gallery grouped wrapped in kanban-wrap (uniform column height + per-column scroll)', "var wrap=document.createElement('div'); wrap.className='kanban-wrap';", 'utf-8'),
    ('#462 global setting default configSaveLocation=both', "configSaveLocation:'both'", 'utf-8'),
    ('#462 settings panel adds 配置保存位置 dropdown with 3 options', "selCfgLoc.appendChild(new Option('两者都保存（默认）','both'));", 'utf-8'),
    ('#462 saveConfig passes saveLocation to C# host', "saveLocation: APP_SETTINGS.configSaveLocation||'both'", 'utf-8'),
    ('#462 C# ViewConfigManager.Save adds saveLocation parameter', "saveLocation", 'utf-8'),
    ('#462 C# ViewConfigManager.DeleteConfigSheet removes embedded sheet', "DeleteConfigSheet", 'utf-8'),
    ('#462 C# ViewConfigManager.DeleteExternalConfigFile removes stale external json', "DeleteExternalConfigFile", 'utf-8'),
    ('#462 C# HtmlMainForm.SaveConfig reads saveLocation from JS', "saveLocation", 'utf-16le'),
    # 注意：C# 类型名/成员名存于 DLL 元数据 #Strings 堆 = UTF-8；只有字符串字面量(#US 堆)才是 UTF-16LE
    ('#428-3/#458 WorkbookConfigFile model (C# type name, metadata=utf-8)', 'WorkbookConfigFile', 'utf-8'),
    ('#428-3/#458 WorkbookConfigFile.LastTableName property (C# metadata)', 'LastTableName', 'utf-8'),
    ('#428-3/#458 GetLastTableName API for JS bootstrap (C# metadata)', 'GetLastTableName', 'utf-8'),
    ('#428-3/#458 legacy per-table config files migrated & merged (C# metadata)', 'MigrateLegacyFiles', 'utf-8'),
    ('#428-4/#459 ExcelAdapter.WriteConfigSheet writes hidden sheet (C# metadata)', 'WriteConfigSheet', 'utf-8'),
    ('#428-4/#459 ExcelAdapter.ReadConfigSheet reads hidden sheet first (C# metadata)', 'ReadConfigSheet', 'utf-8'),
    ('#428-4/#459 ViewConfigManager.SaveWorkbookToSheet embeds config (C# metadata)', 'SaveWorkbookToSheet', 'utf-8'),
    # --- v2.9.37 / #465 画册分组卡片高度统一(禁 flex 压缩) + #466 嵌入配置查看器 ---
    ('#465 grouped column cards must not flex-shrink (uniform card height)', ".kanban-col-body>.kanban-card,.kanban-col-body>.gallery-card{flex:0 0 auto;}", 'utf-8'),
    ('#466 settings panel adds 嵌入配置 viewer entry', "btnCfgView.textContent='查看配置结构与数据'", 'utf-8'),
    ('#466 embedded config dialog implemented', "function showEmbeddedConfigDialog()", 'utf-8'),
    ('#466 dialog reads embedded config via api', "api.call('getEmbeddedConfig',{})", 'utf-8'),
    ('#466 dialog can unhide the very-hidden sheet', "api.call('setConfigSheetVisible',{visible:true})", 'utf-8'),
    ('#466 dialog can save workbook to persist embedded config', "api.call('saveWorkbookFile',{})", 'utf-8'),
    ('#466 dialog explains xlSheetVeryHidden to user', 'xlSheetVeryHidden</b>（深度隐藏）', 'utf-8'),
    ('#466 C# ExcelAdapter.GetConfigSheetInfo (metadata=utf-8)', 'GetConfigSheetInfo', 'utf-8'),
    ('#466 C# ExcelAdapter.SetConfigSheetVisible (metadata=utf-8)', 'SetConfigSheetVisible', 'utf-8'),
    ('#466 C# ExcelAdapter.SaveWorkbookFile (metadata=utf-8)', 'SaveWorkbookFile', 'utf-8'),
    ('#466 C# HtmlMainForm.GetEmbeddedConfig (metadata=utf-8)', 'GetEmbeddedConfig', 'utf-8'),
    ('#466 C# route literal getEmbeddedConfig (string literal=utf-16le)', 'getEmbeddedConfig', 'utf-16le'),
    ('#466 C# route literal setConfigSheetVisible (string literal=utf-16le)', 'setConfigSheetVisible', 'utf-16le'),
    ('#466 C# route literal saveWorkbookFile (string literal=utf-16le)', 'saveWorkbookFile', 'utf-16le'),
    # --- v2.9.38 / 视图右键菜单：另存新视图 / 重命名 / 删除（自带基础视图不可删/改名；用户视图可删/改名）---
    ('视图右键菜单 duplicateView 函数', 'function duplicateView(v)', 'utf-8'),
    ('视图右键菜单 deleteView 函数', 'function deleteView(v)', 'utf-8'),
    ('视图右键菜单 getDefaultViewId 函数', 'function getDefaultViewId()', 'utf-8'),
    ('视图右键菜单 isDefaultView 函数', 'function isDefaultView(v)', 'utf-8'),
    ('视图右键菜单 uniqueViewName 函数', 'function uniqueViewName(base)', 'utf-8'),
    ('视图右键菜单 isUserView 函数（仅用户视图可重命名/删除）', 'function isUserView(v)', 'utf-8'),
    ('视图右键菜单 showViewContextMenu 函数', 'function showViewContextMenu(e, v)', 'utf-8'),
    ('视图右键菜单 renameView 函数', 'function renameView(v)', 'utf-8'),
    ('视图右键菜单 菜单项「另存新视图」', '另存新视图', 'utf-8'),
    ('视图右键菜单 菜单项「重命名」', '重命名', 'utf-8'),
    ('视图右键菜单 菜单项「删除」', '删除', 'utf-8'),
    ('视图右键菜单 自带视图保护提示', '自带视图不可删除', 'utf-8'),
    ('需求1 #492 功能区图标改深蓝 .sidebar-top .btn .ic', '.sidebar-top .btn .ic{color:var(--accent-dark);}', 'utf-8'),
    ('视图右键菜单 #492 自带视图蓝：视图切换名 .view-item .vname', '.view-item .vname{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1;min-width:0;color:var(--accent);}', 'utf-8'),
    ('视图右键菜单 #492 用户视图去色：名 .view-item.user .vname{color:var(--text-2)', '.view-item.user .vname{color:var(--text-2);}', 'utf-8'),
    ('视图右键菜单 #492 用户视图去色：图标 .view-item.user .ic{color:var(--text-2)', '.view-item.user .ic{color:var(--text-2);}', 'utf-8'),
    ('视图右键菜单 #492 用户视图激活态仍蓝 .view-item.user.active .vname', '.view-item.user.active .vname{color:var(--accent);}', 'utf-8'),
    ('视图右键菜单 分隔线 .view-sep', '.view-sep{', 'utf-8'),
    ('视图右键菜单 重命名禁止重名校验', "state.views.some(function(x){ return x.viewId!==v.viewId && (x.viewName||'')===name; })", 'utf-8'),
    ('视图另存 用户视图标志 UserView (C# 元数据 utf-8)', 'UserView', 'utf-8'),
    ('视图另存 duplicateView 标记 userView=true', 'copy.userView=true', 'utf-8'),
    ('视图另存 删除回退到默认视图', "var defId=getDefaultViewId();", 'utf-8'),
    ('视图另存 saveConfig 新增视图合并', "cfg.views.push(JSON.parse(JSON.stringify(sv)));", 'utf-8'),
    ('视图另存 saveConfig 移除已删除视图', "cfg.views=cfg.views.filter(function(cv){ return state.views.some(function(sv){ return sv.viewId===cv.viewId; }); });", 'utf-8'),
    # --- v2.9.38 修正（#487~#492）：残留视图可删 / 另存弹框输名 / 类型+序号命名 / 悬停全名 / 去分隔线 / 自带蓝+用户去色 ---
    ('视图另存 #487 isUserView 前缀兜底 copy/gantt-', '(?:copy|gantt)-', 'utf-8'),
    ('视图另存 #488 另存弹框遮罩 dupViewOverlay', 'dupViewOverlay', 'utf-8'),
    ('视图另存 #488 另存弹框输入框 dupViewInput', 'dupViewInput', 'utf-8'),
    ('视图另存 #488 另存确认后标记 userView=true', "copy.userView=true; // 标记为「另存」产生的用户视图，可重命名 / 删除", 'utf-8'),
    ('视图另存 #489 悬停显示完整名称 it.title=v.viewName', 'it.title=v.viewName', 'utf-8'),
    ('视图另存 #491 类型+序号命名 nextCopyName', 'function nextCopyName(viewType)', 'utf-8'),
    ('视图另存 #491 类型+序号命名正则 var re=new RegExp', "var re=new RegExp('^'+base+'", 'utf-8'),
    ('视图另存 #490 另存项后无分隔线（紧跟重命名）', "duplicateView(v); }); }},\r\n      user ? {label:'重命名'", 'utf-8'),
    # --- 画册分组时去掉卡片顶部色条（分组后列头已有色条）---
    ('画册分组去卡片顶色条 !groupBy && galColor 守卫', '!groupBy && galColor', 'utf-8'),
    # --- v2.9.39 / 图标深蓝 + 日历悬停对齐甘特 + 画册吸收看板分组拖拽（单击不弹详情）---
    # 需求1：窗口左上角 brand 图标 + 功能区(ribbon)图标 改深蓝（新增 --accent-dark 变量，不污染 #492 强调蓝）
    ('需求1 深蓝变量 --accent-dark:#173A8C', '--accent-dark:#173A8C;', 'utf-8'),
    ('需求1 左上角 brand .dot 使用深蓝', 'background:var(--accent-dark);flex:0 0 auto;', 'utf-8'),
    ('需求1 功能区图标 .sidebar-top .btn .ic 使用深蓝', '.sidebar-top .btn .ic{color:var(--accent-dark);}', 'utf-8'),
    # 需求2：日历事件悬停内容对齐甘特条悬停（标题 + 起止日期范围）
    ('需求2 日历悬停函数 calEventTooltip', 'function calEventTooltip(cfg, r){', 'utf-8'),
    ('需求2 日历日事件悬停改用 calEventTooltip', 'ev.title=calEventTooltip(cfg, r);', 'utf-8'),
    ('需求2 日历月分段悬停改用 calEventTooltip', 'seg.title=calEventTooltip(cfg, r);', 'utf-8'),
    # 需求3：画册吸收看板分组自由拖拽 + 实时更新；单击卡片不再自动弹右侧详情面板（看板本体不动）
    ('需求3 画册单击卡片不再弹详情面板', '// #498 画册单击卡片不再自动弹出右侧详情面板', 'utf-8'),
    ('需求3 画册分组复用看板拖拽 enableKanbanDrag', '// #498 画册分组模式复用看板分组自由拖拽 + 实时更新', 'utf-8'),
    ('需求3 画册分组列带 dataset.group（拖拽落点）', "grp.className='kanban-col gallery-group-col'; grp.dataset.group=k;", 'utf-8'),
    ('需求3 画册分组列拖拽悬停高亮 dropover', "if(state._kanbanDragCard) grp.classList.add('dropover');", 'utf-8'),
]
negative_checks = [
    ('#345 gantt fit-to-width(ganttFit)已废弃', "var ganttFit=(dim==='day'", 'utf-8'),
    ('#333 gantt no data-recenter inView jump', 'var inView = !(max<dataMin || min>dataMax);', 'utf-8'),
    ('#339 month drag 1/3 width judgement removed', "(relX > w*2/3)?'resize-end':(relX < w/3?'resize-start':'move')", 'utf-8'),
    ('#340 settings-panel sidebar css removed', '.settings-panel{position:fixed', 'utf-8'),
    ('#343 gantt no whole-view blank on invalid dates', '没有有效的起止日期数据', 'utf-8'),
    ('#350 gantt no longer uses windowed ganttRange for visible range', "var range=ganttRange(dim, ganttState.anchorDate", 'utf-8'),
    ('#14 addGroupValue removed', 'function addGroupValue(v)', 'utf-8'),
    ('#14 ＋分组 removed', '＋分组', 'utf-8'),
    ('C6 add group button removed', 'addGroupValue', 'utf-8'),
    ('#287/#288 minLabelValue no longer gates chart labels', 'g.value > (cfg.minLabelValue || 0)', 'utf-8'),
    ('#319 calendar add button removed', 'cal-add', 'utf-8'),
    ('#352 gantt day no longer hourly ticks', "n.setHours(n.getHours()+6); // 日视图", 'utf-8'),
    ('#352 gantt day no longer hour label', "return pad(t.getHours())+':00';", 'utf-8'),
    ('#354 old hardcoded percentage step removed', "input.step='0.01';", 'utf-8'),
    ('#356 old edge-based month resize detection removed', "var canResize=!!cfg.endDateField && w>=30;", 'utf-8'),
    # #421 旧实现（自由像素拉伸 + .cal-event-resize 基类与日视图纵向条冲突）已彻底移除，以下为负向回归守卫
    ('#421 old free-pixel month drag translate(dx,dy) removed', "ev.style.transform='translate('+dx+'px,'+dy+'px)'", 'utf-8'),
    ('#421 old month handle left base-class collision removed', "hl.className='cal-event-resize cal-event-resize-l'", 'utf-8'),
    ('#421 old month handle right base-class collision removed', "hr.className='cal-event-resize cal-event-resize-r'", 'utf-8'),
    # #412 月视图拖拽改用甘特式"像素→天"换算，脆弱的 elementFromPoint 落点格判定必须彻底移除
    ('#412 month drag elementFromPoint drop-cell removed', "var tCell=tEl?tEl.closest('.cal-cell'):null;", 'utf-8'),
    ('#412 month drag moveDelta(dCols/dRows) removed', 'moveDelta=dCols+dRows*7', 'utf-8'),
    ('#412 month drag cellDate branch removed', 'ne=cellDate?cellDate', 'utf-8'),
    ('#366 global summaryPosition UI removed', "spSel.id='setSummaryPos'", 'utf-8'),
    ('#366 renderSummaryRow no longer uses APP_SETTINGS.summaryPosition', 'APP_SETTINGS.summaryPosition', 'utf-8'),
    ('#367 dashboard top threshold input removed', "setLabelThreshold'", 'utf-8'),  # 仅仪表盘工具条顶部那个（模态窗口用 setLabelThresholdModal）
    ('#370 monthMaxEvents removed from calendar settings', "setMonthMaxCal", 'utf-8'),
    ('#375 C# SaveBitmapAsPdf removed', 'SaveBitmapAsPdf', 'utf-8'),
    ('#375 C# PDF writer header literal removed', '%PDF-1.4', 'utf-16le'),
    ('#375 old clipboard label removed', '复制图表区域图片到剪贴板', 'utf-8'),
    ('#383 old About help text removed', '左侧切换视图 → 顶部', 'utf-8'),
    ('#386 old DatePickerWheelBehavior retired', 'DatePickerWheelBehavior', 'utf-8'),
    ('#386 old EnableFastWheel attached property retired', 'EnableFastWheel', 'utf-8'),
    ('#389 About footer help button removed', 'foot.appendChild(helpBtn)', 'utf-8'),
    # #422 旧实现（事件嵌入单格文档流 + cell.overflow='visible' 伪造跨天 + 宽度/translate 预览）已彻底移除
    ('#422 old embedded-in-cell month event render removed', "monthDragStart(ev, r, cfg, cell, 'resize-start', e)", 'utf-8'),
    ('#422 old month drag overflow:visible hack removed', "cell.style.overflow='visible';", 'utf-8'),
    ('#422 old month drag inline width preview removed', "Math.max(cellW, origW+dd*cellW)+'px'", 'utf-8'),
    ('#422 old month drag translate(dx,dy) preview removed', "ev.style.transform='translate('+dx+'px,'+dy+'px)'", 'utf-8'),
    ('#422 old month drag resize-start translateX preview removed', "ev.style.transform='translateX('+(dd*cellW)+'px)'", 'utf-8'),
    ('#422 old makeMonthEventDraggable removed', "function makeMonthEventDraggable", 'utf-8'),
    ('#422 old monthDragStart(ev,r,cfg,cell,mode,e) signature removed', "monthDragStart(ev, r, cfg, cell, mode, e)", 'utf-8'),
    # #423 旧实现（固定 5 泳道上限 + pickLane 满后回退 lane0 造成重叠）已彻底移除
    ('#423 old fixed 5-lane cap removed', "var maxLanes=APP_SETTINGS.monthMaxEvents||5;", 'utf-8'),
    ('#423 old pickLane(bands) helper removed', "function pickLane(bands){", 'utf-8'),
    ('#423 old pickLane call removed', "var lane=pickLane(bands);", 'utf-8'),
    ('#423 old pickLane fallback return 0 (caused overlap) removed', "      return 0;\n    }\n    rows.forEach(function(r){", 'utf-8'),
    ('#426-4 old per-band needed[bb] max-lane computation removed (replaced by compactNeeded)', "if(ev.lane+1>needed[bb]) needed[bb]=ev.lane+1;", 'utf-8'),
    ('#427-1 old top-strip multiEv/singleEv split removed (unified events system)', "var multiEv=events.filter(function(ev){ return ev.multi; });", 'utf-8'),
    ('#427-1 old MT_STRIP_PADTOP/MT_STRIP_H constants removed', "var MT_STRIP_PADTOP=28;", 'utf-8'),
    ('#427-2 old MT_COLLAPSED_LANES/MT_EXPANDED expand-toggle removed (now +N popup)', "var MT_COLLAPSED_LANES=3;", 'utf-8'),
    ('#427-2 old MT_EXPANDED week-toggle removed (now +N opens popup, no expand)', "MT_EXPANDED[band]=!MT_EXPANDED[band];", 'utf-8'),
    ('#426-3 MT_MAXLANES no longer a module-level constant (now live inside layoutMonthEvents)', "MT_MAXLANES=(APP_SETTINGS.monthMaxEvents && APP_SETTINGS.monthMaxEvents>0)?APP_SETTINGS.monthMaxEvents:8;\n  // #426-3", 'utf-8'),
    ('#413 cal-cell fixed 120px min-height removed (adaptive row heights now in JS)', 'min-height:120px', 'utf-8'),
    ('#NEW auto row-height fr-fill removed (rows now fixed px = content height, no busy-week balloon)', "frw[i]+'fr'", 'utf-8'),
    # #424 旧实现（全局按事件隐藏 + fr 比例行高）已彻底移除，以下为负向回归守卫
    ('#424 old global hidden[ev.r.rowIndex] removed (now per-band)', "if(hidden[ev.r.rowIndex]) return;", 'utf-8'),
    ('#424 old fr row-height weights removed (now minmax(nat,fr))', "grid.style.gridTemplateRows='auto '+weights.map(function(w){return w+'fr';}).join(' ');", 'utf-8'),
    ('#425 no clientHeight pixel-measurement row height (caused cal-dow stretch gray gap)', "var avail=grid.clientHeight - HEADER - 6; if(avail<0) avail=0;", 'utf-8'),
    ('#424-3 old surplus-inflation into weeks removed (no huge blank blocks)', "avail-sumD)*(surplus[i]/sumSurplus)", 'utf-8'),
    ('#424-3 old single-number data-row view-switch locator removed (now JSON-aware)', "sel='tr[data-row=\"'+rowIndex+'\"]';", 'utf-8'),
    # --- v2.9.35 / #428-2 旧「+N 弹列表」实现已彻底删除（#428-2 改为点击直接展开该周），以下为负向回归守卫 ---
    ('#428-2 old showMonthMorePanel function removed', "function showMonthMorePanel", 'utf-8'),
    ('#428-2 old +N popup click handler removed (now expands week)', "moreEl.addEventListener('click', function(e){ e.stopPropagation(); showMonthMorePanel(grid, cfg, moreEl, band, count); });", 'utf-8'),
    ('#428-2 old monthMorePop popup element id removed', "var pop=document.createElement('div'); pop.id='monthMorePop';", 'utf-8'),
    ('#428-2 old #monthMorePop cleanup selector removed', "'.cal-event-seg, .cal-month-more, #monthMorePop'", 'utf-8'),
    ('#428-1 old vertical gallery-group-host container removed (now kanban horizontal cols)', "gallery-group-host", 'utf-8'),
    ('#428-2 old fixed 6-equal-share row height removed (now rowSpecs with expandable week)', "grid.style.gridTemplateRows='30px repeat(6,1fr)';", 'utf-8'),
    ('#428-2 old unconditional lane fold removed (now skips expanded weeks)', "if(laneCount[b]>K){", 'utf-8'),
    ('#428-3/#459 old per-table split config filename suffix removed', "suffix = string.IsNullOrWhiteSpace(tableName) ? \"\" : \"-\" + SanitizeFileName(tableName);", 'utf-8'),
    # #467 SourceFile 改为仅存文件名（Path.GetFileName）：下列负向守卫确保没有把完整磁盘绝对路径硬编码进 DLL（utf-16le 字面量）。
    # 若有人把 workbookPath 直接序列化或硬编码绝对路径，下列会 FAIL。
    ('#467 不应硬编码完整磁盘绝对路径字面量（utf-16le）', r'D:\编程开发\开源项目\多维表分析软件\多维表测试数据_插件测试.xlsx', 'utf-16le'),
    # --- v2.9.38 / 视图另存为新视图：图表视图旧内联删除（直接 splice + confirm）已改为复用 deleteView(v)，确保下列旧实现被移除 ---
    ('视图另存为新视图 图表旧内联删除已移除', "if(confirm('确定删除当前统计图表视图？')){ var idx=state.views.findIndex(function(x){return x.viewId===v.viewId;}); if(idx>=0){ state.views.splice(idx,1); saveConfig(); renderSidebar(); renderContent(); toast('已删除'); } }", 'utf-8'),
    # --- v2.9.38 修正 #490：视图右键菜单「另存新视图」项下方不再有分隔线（旧实现另存项后紧跟 {sep:true}）---
    ('视图另存 #490 旧另存项下分隔线 {sep:true} 已移除', "duplicateView(v); }); }},\r\n      {sep:true},", 'utf-8'),
    # --- v2.9.39 修正：日历悬停改为对齐甘特（旧实现已彻底移除，以下为负向回归守卫）---
    ('需求2 日历日事件旧悬停 title+timeStr 已移除', "ev.title=title+", 'utf-8'),
    ('需求2 日历月分段旧悬停仅 title 已移除', "seg.title=title;", 'utf-8'),
]
all_ok = True
for label, s, enc in checks:
    ok = has(s, enc)
    print(('OK   ' if ok else 'FAIL ') + label)
    if not ok:
        all_ok = False
for label, s, enc in negative_checks:
    ok = missing(s, enc)
    print(('OK   ' if ok else 'FAIL ') + label)
    if not ok:
        all_ok = False
sys.exit(0 if all_ok else 1)
